### ISSUE TITLE
met ERROR998 when crawling BW

### ISSUE THREAD

**Issue by AlphaLiu** [xuzhengyi1995/Manga_downloader#1]
It is often met ERROR998 when crawling BW/TW, any chance to solve it??

**Comment by xuzhengyi1995** [comment]
This is BW's problem, you can only open a manga on one browser at the same time, when you meet this problem, please close the manga on all browser -> log out -> log in -> verify that this manga can be opened without error -> copy cookies -> download.

Unfortunately, there are not very efficient way to solve this problem. The only way I knew is log out and log in again.
