### ISSUE TITLE
[Request] https://ebook.tongli.com.tw/serials

### ISSUE THREAD

**Issue by FlotingDream** [xuzhengyi1995/Manga_downloader#102]
In "https://ebook.tongli.com.tw/serials"
can read several free chapter (updating).

The new chromium based way, can get the "f0001ba" like files in "\bw-downloader-profile\Default\Cache\Cache_Data"
And after add '.jpg' ext. It is readable "1128*1600" jpg images.
However, the page order is wrong.

by the way in F12-console-networks-Fetch/XHR  the temporary url like 
"https://tongli-ebook-cdn.azureedge.net/comic/B616FEB9200E4598F3C208DA8013D2F6/10?sv=2020-08-04&sr=b&st=2022-08-19T05:04:11Z&se=2022-08-19T05:09:41Z&sp=r&spr=https&rsct=binary&sig=Vc16PPaFt2vT7XlRTZdawjlmXxV4sud2xbzEJ1LIDuc%3d"

"https://tongli-ebook-cdn.azureedge.net/comic/B616FEB9200E4598F3C208DA8013D2F6/15?sv=2020-08-04&sr=b&st=2022-08-19T05:04:11Z&se=2022-08-19T05:09:41Z&sp=r&spr=https&rsct=binary&sig=8ByuLsV%2fyc0HKtrEcsrLtehoAOXRmZ%2bDoGFqqx6UVMo%3d"

the "10?" in the url give the page number 10.
the "15?" in the url give the page number 15.

Request for the support for 'https://ebook.tongli.com.tw/serials' 

Thx!
:)

**Comment by xuzhengyi1995** [comment]
This is much easier than get image from canvas, we could do something [here](https://source.chromium.org/chromium/chromium/src/+/main:/third_party/blink/renderer/platform/loader/fetch/resource_loader.h), check the resource URL and save it to disk.

Will implement this and update a new version.

**Comment by xuzhengyi1995** [comment]
Finished, will upload in the release shortly, use method is same as BW.
![image](https://user-images.githubusercontent.com/29002064/185739060-0e0beba6-80aa-4b2c-a260-8e4137bd704a.png)
