### ISSUE TITLE
[Site Request] DMM Books (works with Selenium)

### ISSUE THREAD

**Issue by Lowell12345** [xuzhengyi1995/Manga_downloader#108]
![ff](https://user-images.githubusercontent.com/98024707/190146203-90c7ae9a-0743-4bb2-87d8-0799caff626a.png)

I tried DMM Books with same method with Bookwalker's and I was available to get images, but it doesn't move the pages automatically. 
Can get the images when I press the ← button but wonder if you can add page move here?

Hope you guys can help with this one. 

sample : https://book.dmm.com/tachiyomi/?cid=FRNfXRNVFW1RAQxaCgZWUAoBRQYDClYAThFfCUJYU1kCCERYCmkGUFcKWhRHVwVfCBxZW1kEVQ__&lin=1&sd=0

**Comment by xuzhengyi1995** [comment]
For DMM please user `window.i=0;setInterval(()=>{NFBR.a6G.Initializer.views_.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)`

**Comment by Lowell12345** [comment]
It works so well. Thank you so much!
