### ISSUE TITLE
Certain Manga will not rip/DL from bookwalker.jp

### ISSUE THREAD

**Issue by admiralkikan** [xuzhengyi1995/Manga_downloader#113]
Here's a list I know wont download. Jump series of any title will not download for sure. There weren't any errors of note that popped up. Any error that came up were the same stuff that popped for the manga I could rip/dl from my account. Current version of manga downloader used. Also, the new line for cmd will not auto change page. The old line does work but not all the time. Which for me doesn't matter since I catch the pages that end up not downloading and I can go back to do so sooner when I manually change the page. If you have any questions let me know and I will try to answer them.

Spy x Family
うる星やつら〔新装版〕
神のみぞ知るセカイ（少年サンデーコミックス）
DRAGON BALL モノクロ版
モネさんのマジメすぎるつき合い方 セミカラー 分冊版
侵略！イカ娘
R-15（角川コミックス・エース）
グレネーダー（角川コミックス・エース）
FORTUNE ARTERIAL（角川コミックス・エース）
かのこん（MFコミックス　アライブシリーズ）
GIRLSブラボー（角川コミックス・エース）
ケメコデラックス！
ＵＮ‐ＧＯ～因果論（角川コミックス・エース）
けいおん！
この中に１人、妹がいる！（MFコミックス　アライブシリーズ）
ニセコイ（ジャンプコミックスDIGITAL）
HUNTER×HUNTER モノクロ版
いけない二人とはじめての罰（コミックヘヴン）
ヨガクレ
ペンコイ

**Comment by xuzhengyi1995** [comment]
Just bought the Spy x Family and seems that there is some problem, investigating.

**Comment by admiralkikan** [comment]
I can only assume it will be the same issue for all of them. Unless for whatever reason BW did something to Jump series specifically. Good luck in finding the issue.

**Comment by xuzhengyi1995** [comment]
Found the problem, the reason is very simple, the image of these manga has a poor resolution (width less than 800px) and is filtered by the program😂 , has fixed this and will update the program shortly.

The moving page script seems work for me, the new js in the file above is for dmm, bw should use this one:
```js
window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)
```

**Comment by xuzhengyi1995** [comment]
> I can only assume it will be the same issue for all of them. Unless for whatever reason BW did something to Jump series specifically. Good luck in finding the issue.

Please try the [new version](https://github.com/xuzhengyi1995/Manga_downloader/releases/tag/BW-downloader-chrome-v0.3), thanks.

**Comment by admiralkikan** [comment]
I see. Seems odd that SPYxFAMILY would be that low of a resolution. or for that matter some of those titles. I have Nagasarete Airontou completed and the 1st volume isn't even less than 800px uploaded in 2013. Which looks to be the earliest date I have.

I'll give it a try right now

**Comment by admiralkikan** [comment]
Alright seems to be working, If I see anything that's off I will let you know. I wonder why SxF such low quality. lol

Need to figure out a way to get Hi-Res copies aside from Viz to color. xD

**Comment by xuzhengyi1995** [comment]
> I see. Seems odd that SPYxFAMILY would be that low of a resolution. or for that matter some of those titles. I have Nagasarete Airontou completed and the 1st volume isn't even less than 800px uploaded in 2013. Which looks to be the earliest date I have.
> 
> I'll give it a try right now

Yes, some old manga got a very good resolution, maybe this is not related to publish date 😂.

> I do have one question though. Are cover pages still not able to be ripped?

The cover page is not encrypted and should use another code route to download, it is not very complicate to support because it is just read the data and write to file (Already write the code for `tongli.com.tw`). Will try to implement this in next version.

**Comment by admiralkikan** [comment]
Lol Jump just being stingy with their manga resolution outside of Jump+. idk where the 2100px version of vol.1 Raw came from. Might be upscaled but not from digital shops or English. File size is too big compared to English.

**Comment by xuzhengyi1995** [comment]
> Lol Jump just being stingy with their manga resolution outside of Jump+. idk where the 2100px version of vol.1 Raw came from. Might be upscaled but not from digital shops or English. File size is too big compared to English.

2100px is really high and maybe is upscaled, I don't really think someone is still using a scanner to scan the paper book nowadays 😂
