### ISSUE TITLE
Experiencing Viewing Issues In Chromium

### ISSUE THREAD

**Issue by theaniman** [xuzhengyi1995/Manga_downloader#114]
Good day!  I've appreciated your efforts with this downloader for my purchased volumes and the updated free volumes available on Bookwalker, thank you so much!  However, starting today, Chromium had viewing issues with several of the free volumes; I came here, updated to v0.3, tried again, downloaded computer updates and restarted, then tried again... at each step, the result was the same:  viewing the manga volumes in Chrome produced no problems, but trying to view them in Chromium has issues.  I hope this detail can help:

キャプテン2 (newly free in past 24 hours) - https://bookwalker.jp/de76598ad4-a888-4638-b3e8-ae3c4efe00d7/?sample=2 - No problems at all.

シャドークロス (newly free in past 24 hours) - https://bookwalker.jp/de40e88a86-c761-4a88-a47b-ecb5401cd12b/?sample=2 - Volume opens, pages consistently stop loading after page ~31/32 and then will just display the "LOADING" background.  Volume can still be navigated and going back to previously loaded pages shows them properly.  If I open the link in another tab after navigating, the new tab will save the next ~30 images from the resumed page number and then repeat the loading issue.  Not sure why this is "timing out" after 30 pages.

プレイボール (newly free in past 24 hours) - https://bookwalker.jp/dec628ce29-b0f4-48a2-afab-d924e15ae6f2/?sample=2 - Volume will not open, loading circle disappears and then horizontal loading line never shows, page is left on white background and there are no pages to navigate.

Again, opening these in Chrome produced no viewing errors, so I'm not sure what to focus on other than an issue with Chromium, or how Bookwalker is loading some volumes.  I tried a volume of my own library, the English version of Skip and Loafer volume 1 (https://global.bookwalker.jp/de1aa80d72-a358-46a1-b4bb-c7bb2f445ab0/skip-and-loafer-vol-1/), and it also would not load, while there were no problems when I originally purchased it months ago.  I haven't checked my own library further, was only interested to see if the same issue would affect my library and it can.

Edit: Any trial viewers I've opened work just fine, I understand these are different from the volumes but thought this might be useful too.

Really hoping this isn't a problem on my end, I've tried a decent amount of possibilities but only decided to post once I couldn't get different results, I hope these errors can be replicated by someone else.  If more detail or other examples are helpful, let me know.  Thank you!

**Comment by xuzhengyi1995** [comment]
I just tried プレイボール and it seems that it is working well and could not re-produce this problem.
![image](https://user-images.githubusercontent.com/29002064/203531962-44c2e489-3db0-441e-8f6f-29f7e5e68747.png)

I would recommend to delete the `C:\bw-downloader-profile` and try again, sometimes the profile got corrupted and will lead to some strange errors.

**Comment by theaniman** [comment]
Really, thank you so much for the quick reply and continued work with this.  You were exactly correct, the old profile somehow had a problem, I had no errors trying each example using a fresh profile.  I'm both embarrassed and relieved that the problem was that simple!  Now that I have a better understanding of how this may affect results I will be sure to try a fresh profile when troubleshooting any future issues on my end.  :)
