### ISSUE TITLE
cmoa 好像有点问题

### ISSUE THREAD

**Issue by transpinx** [xuzhengyi1995/Manga_downloader#13]
![003](https://user-images.githubusercontent.com/51951550/92212275-52e59600-eec4-11ea-969b-8e977b4732bc.png)
我随便举个例子
这图从上往下看 1/3 和 2/3 的位置都有部分像素是重复的
好像大概是 4px 的样子

**Comment by xuzhengyi1995** [comment]
您好，
感谢您的提问！
确实，coma的漫画是将一张分为3个部分进行拼接的，当时做的比较着急，没有仔细研究coma拼接的规则，我将在假期中对其进行修复。
谢谢！

**Comment by zhongfly** [comment]
将相关代码中的拼接高度减去4px后没有重复了

**Comment by xuzhengyi1995** [comment]
非常感谢帮助修正错误，谢谢！
