### ISSUE TITLE
Opening browser from powershell, Complete newbie

### ISSUE THREAD

**Issue by Truenntaya** [xuzhengyi1995/Manga_downloader#132]
So I've got Chrome-bin unzipped into C:, however just entering 

.\chrome.exe --user-data-dir=c:\bw-downloader-profile --no-sandbox

into powershell doesn't open the browser. I know I can run the browser because I just opened it straight from the exe file but I know that's not how this works. I know there's something I'm missing, but I'm very new to powershell commands. I'm on windows 10 and used the free trial of the most current version of winzip to unzip it. Do I need to unzip it somewhere else?

**Comment by xuzhengyi1995** [comment]
Maybe you should use `cd` to switch to the unzipped dir so the `.\chrome.exe --user-data-dir=c:\bw-downloader-profile --no-sandbox` will work, or you can also try to use the full path like `C:\xxx\xxx\xxx\chrome.exe  --user-data-dir=c:\bw-downloader-profile --no-sandbox.

**Comment by Truenntaya** [comment]
Ok, that worked! Unfortunately, now I'm getting an issue with trying to download the manga. I'm opening the browser and opening it onto the manga, then using the command the readme says to use for bookwalker. This one:

  window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)

and I'm getting this error message:

At line:1 char:27
+   window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a ...
+                           ~
An expression was expected after '('.
At line:1 char:27
+   window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a ...
+                           ~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression

I've tried just deleting the parentheses it's mad about but then it throws a different error code related to the =>. If this isn't how you're supposed to bring up a second, following issue lmk and I'll post this the appropriate way

**Comment by Cosmiet** [comment]
You are supposed to paste that code snippet in the google chrome console.
Go to the the manga viewer page in chrome and press **Ctrl + Shift + i** then paste the code snippet in the window that opens.
