### ISSUE TITLE
cmoa 还是有问题

### ISSUE THREAD

**Issue by transpinx** [xuzhengyi1995/Manga_downloader#17]
上次 #13 我报错说 cmoa 有中间有部分像素重复了
然后你们就让 cmoa 的三段图片都减掉 4px 了对吧
最下面那张的下方不用减掉 4px 啊
现在每张都少掉 4px 的内容了

**Comment by persia7emily** [comment]
虽然很好用，但CMOA确实多切了图片……
![Uploading 2020-11-16_190015.png…]()

**Comment by persia7emily** [comment]
打开website_actions文件夹里的cmoa_jp_actions.py
把第66行imgs_height.append(height+imgs_height[-1]-4)的【-4】去掉就行了

**Comment by persia7emily** [comment]
附议。

第1、2段需要减4px，但是第3段不需要，导致最后成品图底部切边。

**Comment by mtakam** [comment]
The issue is in cmoa, image is short by 4px and the solution is to fix line 68 right?
Do I have to fix it by myself or it already been done?

Do I understand correctly? I'm using google translate.

**Comment by persia7emily** [comment]
> The issue is in cmoa, image is short by 4px and the solution is to fix line 68 right?
> Do I have to fix it by myself or it already been done?
> 
> Do I understand correctly? I'm using google translate.

yes, you're right. if you find the image losing 4px at bottom, you can edit cmoa_jp_actions.py to fix it. 

`        **mmset = 4**   # _normal 4, for bigger images it maybe 6_
        for i in image_elements:
            blob_url = i.get_attribute('src')
            image_data = self.get_file_content_chrome(driver, blob_url)
            part_img = pil_image.open(BytesIO(image_data))
            imgs_arr.append(part_img)
            width, height = part_img.size
            imgs_height.append(height + imgs_height[-1] - **mmset**)

        last_img_height = imgs_height.pop() + **mmset**`

**Comment by xuzhengyi1995** [comment]
@persia7emily Thank you so much, now it got fixed.
