### ISSUE TITLE
"Reject insecure SameSite=None cookies"

### ISSUE THREAD

**Issue by whiteangel123** [xuzhengyi1995/Manga_downloader#2]
I got this message from the command prompt, and then it failed to download. Is this a problem?

[0603/002042.115:INFO:CONSOLE(0)] "A cookie associated with a cross-site resourc
e at http://im-apps.net/ was set without the `SameSite` attribute. A future rele
ase of Chrome will only deliver cookies with cross-site requests if they are set
 with `SameSite=None` and `Secure`. You can review cookies in developer tools un
der Application>Storage>Cookies and see more details at https://www.chromestatus
.com/feature/5088147346030592 and https://www.chromestatus.com/feature/563352162
2188032.", source: https://www.cmoa.jp/ (0)

**Comment by xuzhengyi1995** [comment]
Normally this doesn't matter, you can upload the `error.png` if it failed to download and I'll see if there is some problem, thank you!

**Comment by whiteangel123** [comment]
It turns out it was caused by network error. 
It works now, thank you!

**Comment by xuzhengyi1995** [comment]
Maybe you can also try a VPN if this is a network problem, thank you!

**Comment by whiteangel123** [comment]
It works now! Thank you <3

**Comment by xuzhengyi1995** [comment]
You are welcome :)
