### ISSUE TITLE
BookWalker 是不是用不了了？

### ISSUE THREAD

**Issue by persia7emily** [xuzhengyi1995/Manga_downloader#28]
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by xuzhengyi1995** [comment]
您好，
有时Chrome会自动升级，导致ChromeDriver与当前Chrome版本不匹配。
还请检查您的Chrome和ChromeDriver版本是否匹配，如果不匹配，可能会出现该错误。
谢谢。

**Comment by persia7emily** [comment]
> 您好，
> 有时Chrome会自动升级，导致ChromeDriver与当前Chrome版本不匹配。
> 还请检查您的Chrome和ChromeDriver版本是否匹配，如果不匹配，可能会出现该错误。
> 谢谢。

确定是最适版本，因为天天用。失败了一天一夜，现在试了下Bookwalker又可以了……
谢谢作者，特别好用。
