### ISSUE TITLE
Having issues while extracting from bookwalker.jp (TimeoutException)

### ISSUE THREAD

**Issue by minami29** [xuzhengyi1995/Manga_downloader#29]
![image](https://user-images.githubusercontent.com/35743714/113228263-127fa800-925a-11eb-86fa-9d3f9879d0ca.png)
Here is the screenshot for it, days ago the script is still working.

**Comment by xuzhengyi1995** [comment]
Hello,

Please check #30 and #32 , maybe it's a chrome driver version mismatch, you can redownload the chrome driver [here](https://sites.google.com/a/chromium.org/chromedriver/downloads)

Thank you!
