### ISSUE TITLE
Cookie-based login in cmoa doesn't work?

### ISSUE THREAD

**Issue by Rouryi** [xuzhengyi1995/Manga_downloader#3]
I took the cookie from the request header of the following file(`and.cmoa.jp/auth/resp?janrain_nonce=YYYY-MM-DDXXXXXXXXXXXXXXXXXXXXX`) and wrote it to the configuration file, but it probably failed to log in.
That cookies start with `nmid=XXXXXX`.
In BW, I was getting cookies from a file called "profile", but in Cmoa, which file should I get cookies from?

The image download function was successful, but the login failed, so the sample cartoon was downloaded.

**Comment by xuzhengyi1995** [comment]
Thank you for your question.
For coma, you can just login and get the cookies from the index.
You can check the part `2. Add your cookies in the program.` in `README.md`:

2.  Add your cookies in the program.

    **Remember to use F12 to see the cookies!**

    **Because some http only cookies can not be seen by javascript!**

    **Remember to go to the links below to get the cookies!**

    1.  For [Bookwalker.jp] cookies, go [here](https://member.bookwalker.jp/app/03/my/profile).
    2.  For [Bookwalker.com.jp] cookies, go [here](https://www.bookwalker.com.tw/member).
    3.  For [www.cmoa.jp] cookies, go [here](https://www.cmoa.jp/). 

    > 1.  Open the page.
    > 2.  Press F12.
    > 3.  Click on the _Network_.
    > 4.  Refresh the page.
    > 5.  Find the first _profile_ request, click it.
    > 6.  On the right, there will be a _Request Headers_, go there.
    > 7.  Find the _cookie:...._, copy the string after the _cookie:_, paste to the _main.py_, _YOUR_COOKIES_HERE_

![image](https://user-images.githubusercontent.com/29002064/84033111-ef35f480-a9ca-11ea-8736-54458bcbc105.png)

**Comment by Rouryi** [comment]
Thank you.
This program is fine.
I made a change to the program by mistake and that caused this problem.

I add the following options to chrome options :_(
`option.add_argument('incognito')`

**Comment by mtakam** [comment]
Hello @Rouryi

I'm having the same problem as yours. May I ask how did you do it? I followed the instruction on how to get cookies from the front page and I didn't made any change on the program.

**Comment by Rouryi** [comment]
Hello @mtakam
Open the "https://www.cmoa.jp/auth/login/" page and press F12 to open the developer tools.
Then login.
If you look at the cookie in the request header of the appropriate file (e.g. png), you should see something that says "nmid=****".
This is the cmoa cookie.

**Comment by mtakam** [comment]
Hi,

I did as you told but it still download only sample. TT
Though, the cookies start with "nmid=", I also cleared cookies before tried it again but doesn't work....

I don't know what to do next. I'm also discussion this problem in #38 

Thank you for your help.

**Comment by xuzhengyi1995** [comment]
Hello,

Because I can not buy manga on coma, @Rouryi could you try to run it for coma once again and give a feedback? Thanks a lot.

I will also just check the login function later.

Thank you all!

**Comment by Rouryi** [comment]
Hello.
I just tried it myself and was able to download the purchased items.
https://i.postimg.cc/SRw0kwgY/cmoa.png

**Comment by mtakam** [comment]
Hello,

I'm very new to Python, so I followed the instruction on how to use step by step.

I install selenium, pillow and undetected_chromedriver, though I'm not sure if I have to do all of [these](https://selenium-python.readthedocs.io/installation.html).
<img width="199" alt="pip" src="https://user-images.githubusercontent.com/82701188/115541080-e9868c00-a2c8-11eb-8b65-25eb85141746.png">

@xuzhengyi1995 You can buy [AoT Vol.1-3](https://www.cmoa.jp/title/41198/vol/1/) or [Ase to sekken Vol.1-3](https://www.cmoa.jp/title/156072/vol/1/). They are free until 22 Apr GMT+9 Japan Time.
After they are not free, you can try download them.

Thank you very much for your help!

**Comment by xuzhengyi1995** [comment]
Thank you so much @Rouryi , I have also tried the new version 3 times and there seems no problem.

![image](https://user-images.githubusercontent.com/29002064/115551153-3d9b6b80-a2dd-11eb-96c6-3da297c34564.png)
![image](https://user-images.githubusercontent.com/29002064/115551664-f9f53180-a2dd-11eb-9fc3-8bb8f638f84f.png)

@mtakam , Please check if your cookie is like the below (I get the cookie just from the request to `coma.jp`):
![image](https://user-images.githubusercontent.com/29002064/115551924-46d90800-a2de-11eb-8c9e-9e26d421ded6.png)

You can also check whether your cookie has all the fields below:
```json
[
    "nmid",
    "_cmoa_web_",
    "BIGipServer~I090~Pool_Cmoa_App_On",
    "BIGipServer~I090~Pool_Cmoa_Static_On",
    "_pte_1h_cook",
    "IDS_CMOA",
    "_cmoa_member_back_url_",
    "TS01401464",
    "TS01aa86c0",
    "TS0127b603",
    "TS016f3b3b",
    "ok_url",
    "_cmoa_login_session_token_",
    "mhuid",
    "_gender_",
    "gmopdmp_l",
    "_chrg_kbn_",
    "TS01b31523",
    "_notice_",
    "_cmoa_title_purchase_confirm_[return_url]",
    "_items_in_cart_",
    "_bookshelf_disp_info_",
    "_cmoa_hid_",
    "_shid_",
    "_cmoa_sid_",
    "_ssid_",
    "TS017350e1",
    "__utma",
    "__utmc",
    "__utmz",
    "__utmt",
    "__utmb"
]
```

You can use this small function to help you:

```python
def get_cookie_dict(cookies):
    cookies = cookies.split('; ')
    cookies_dict = {}
    for i in cookies:
        kv = i.split('=')
        cookies_dict[kv[0]] = kv[1]
    return cookies_dict
```

just use a shell and type `python` to run python, copy and past the function above, then:

```python
x='YOUR_COOKIES_HERE' #Enter
get_cookie_dict(x).keys() #Enter
```

Then you can get a list of the field, try to compare with the above.

Maybe you can also try to use a vpn and see it help or not.

Thank you.

**Comment by xuzhengyi1995** [comment]
I have tried and I think I can't login either, I will try to find out why, Thank you!

**Comment by xuzhengyi1995** [comment]
Hello,

I have fixed the problem, but for cmoa we should use the plug-in to get the cookies.
-    For [www.cmoa.jp] cookies, go [here](https://www.cmoa.jp/) and you **must** get cookies by plug-in [EditThisCookie](http://www.editthiscookie.com/), download it for chrome [here](https://chrome.google.com/webstore/detail/edit-this-cookie/fngmhnnpilhplaeedifhccceomclgfbg).
-   For `EditThisCookie`, this can be used in any website above, but for `cmoa` you **must** use this method

    1.  Go to user preferences (chrome-extension://fngmhnnpilhplaeedifhccceomclgfbg/options_pages/user_preferences.html) of `EditThisCookie`
    2.  Set the cookie export format to `Semicolon separated name=value pairs`
    3.  Go to [cmoa](https://www.cmoa.jp/), click the `EditThisCookie` and click `export` button
    4.  Copy the cookies in the file (**After the `// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm`**) into the program

Finally I downloaded the whole [AoT Vol.1-3 ](https://www.cmoa.jp/title/41198/vol/1/):

![image](https://user-images.githubusercontent.com/29002064/115571665-ca502480-a2f1-11eb-8515-16b1612f5c94.png)

If not login, it only has 56 pages.

Thank you!

**Comment by mtakam** [comment]
It works perfectly. Thank you very much!!
