### ISSUE TITLE
Can't download bought manga from cmoa.jp

### ISSUE THREAD

**Issue by mtakam** [xuzhengyi1995/Manga_downloader#38]
It download only free sample. Maybe the problem is about log-in cookie?
I followed the instruction on the front page but it doesn't work.
How can I download the whole thing that I bought?

PS. Thank you very much for your hard work on this project, I'm really appreciate it.

**Comment by xuzhengyi1995** [comment]
Hello,

Thank you for your message.

If you got an error 998, I think you got the right cookie but should wait some time to download, see #36 

If you have problem with getting the cookies, you can refresh the page and get the request cookies for the `profile` (BW JP) or `member` (BW TW) like below, **the index.view should be /profile or /member**

![image](https://user-images.githubusercontent.com/29002064/115168560-fbf89e00-a0ed-11eb-92ca-28ed00cf6328.png)

Thank you.

**Comment by mtakam** [comment]
Thank you for your response.

I get the cookies from www.cmoa.jp but there is no **profile** or **member**. I tried from my account page (https://www.cmoa.jp/mypage/mytop/) too, but there aren't either.
<img width="481" alt="Screenshot 2021-04-19 160710" src="https://user-images.githubusercontent.com/82701188/115212224-79da9a80-a12a-11eb-8a76-c88fb3f95293.png">

and there's always this error at the bottom, I don't know of it's related.
> [ERROR](root) 2021-04-19 16:12:05 : This website has not been added...
Traceback (most recent call last):
  File "C:\Users\Acer\Desktop\Manga_downloader-master\main.py", line 41, in <module>
    downloader.download()
  File "C:\Users\Acer\Desktop\Manga_downloader-master\downloader.py", line 194, in download
    self.check_implementation(t_manga_url)
  File "C:\Users\Acer\Desktop\Manga_downloader-master\downloader.py", line 78, in check_implementation
    raise NotImplementedError
NotImplementedError

**Comment by xuzhengyi1995** [comment]
Hello,

If you got an error like this, it seems that it is not a cookie problem but an url problem, the manga/novel url should contain the string below:

> For coma manga: `cmoa.jp/bib/speedreader`
> For coma novel: `cmoa.jp/bib/reader`

>For [Cmoa.jp]
>
>Open the Manga and just copy the URL on the browser.
>
>The manga URL like this : https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000156072_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Fmypage%2Fmypage_top%2F%3Ftitle%3D156072

If they have updated their website, please let me know.

Thank you.

**Comment by mtakam** [comment]
Hi,

About the error, I used your url in the example but I still got the same error. Though, the download is normal. There is no problem with it.

So I'm using the correct cookies but I still can't download the whole manga I bought. It download only free sample. What did I do wrong? TT

**Comment by xuzhengyi1995** [comment]
> Hi,
> 
> About the error, I used your url in the example but I still got the same error. Though, the download is normal. There is no problem with it.
> 
> So I'm using the correct cookies but I still can't download the whole manga I bought. It download only free sample. What did I do wrong? TT

Hello,

Could you post your url that you copied into the program here? I will check if there is any change.

Thank you

**Comment by mtakam** [comment]
Hi,

This is a chapter I bought, it has 33 pages. But when I place it in the program, it download 10 pages of free sample.
[https://www.cmoa.jp/bib/speedreader/speed.html?cid=0000150170_jp_0001&u0=0&u1=0&rurl=https%3A%2F%2Fwww.cmoa.jp%2Fmypage%2Fmypage_top%2F%3Ftitle%3D150170](url)

Thank you very much for your help.

**Comment by xuzhengyi1995** [comment]
Hello,

There is no `NotImplementedError` during downloading and can download the first 10 free pages at this time ? If yes then it is a cookie problem.

If the cookie from `coma.jp` not work, you can also try to get the cookie from the manga url, use the same method and copy the request cookies from the first request.

Normally this should work, please be careful when you copy the cookie, you can also right click the cookie and then click the `Copy Value`, then past into it here (Below is just an example):

```python
'cookies': '_ga=xxxxx; sidebar_collapsed=false; auto_devops_settings_dismissed=true;_gitlab_session=xxxx',
```

Normally this should work, if it still not work, please let me know and I will try it later.

Thank you.

**Comment by mtakam** [comment]
Hi,

> There is no `NotImplementedError` during downloading and can download the first 10 free pages at this time ? If yes then it is a cookie problem.
>
> If the cookie from coma.jp not work, you can also try to get the cookie from the manga url, use the same method and copy the request cookies from the first request.

Yes, it is. I tried both cookie from www.cmoa.jp and the manga url. It still the same. TT

The problem is the cookies for sure. My cookies starts with

1. Before clear cookies www.cmoa.jp
BIGipServer~I090~Pool_Cmoa_App_On=xxx; BIGipServer~I090~Pool_Cmoa_Static_On=xxx
2. After clear cookies from www.cmoa.jp and manga url
nmid=xxx; BIGipServer~I090~Pool_Cmoa_App_On=xxx; BIGipServer~I090~Pool_Cmoa_Static_On=xxx
3. After clear cookies from [my page](https://www.cmoa.jp/mypage/mypage_top/)
solmale_myshelf_exp=open; nmid=xxx; BIGipServer~I090~Pool_Cmoa_App_On=xxx; BIGipServer~I090~Pool_Cmoa_Static_On=xxx

I'm not sure these are the right cookies so I put some example for you. They are very long, around 5xxx characters.

Thank you very much.

Ps. There is no middle line for I090, it is ~ I090 ~ without space.

**Comment by xuzhengyi1995** [comment]
Fixes, Please see [here](https://github.com/xuzhengyi1995/Manga_downloader/issues/3#issuecomment-824111868), thank you!
