### ISSUE TITLE
Bookwalker-cannot read property 'menu' of undefined 

### ISSUE THREAD

**Issue by beffy3** [xuzhengyi1995/Manga_downloader#40]
I'm having some problems with ripping from Bookwalker, specifically with this:
![rsfgfd](https://user-images.githubusercontent.com/82968512/115697529-fb3e6100-a3a6-11eb-863e-29e900c98654.JPG)
The error.png has the start of the manga with a request for cookies at the bottom if that adds to anything. I've tried logging in and out and running the code multiple times but the same error keeps popping up. 
By the way, thanks for coming up with this script! I normally use it for CMOA and it works like a charm :)

**Comment by xuzhengyi1995** [comment]
> I'm having some problems with ripping from Bookwalker, specifically with this:
> ![rsfgfd](https://user-images.githubusercontent.com/82968512/115697529-fb3e6100-a3a6-11eb-863e-29e900c98654.JPG)
> The error.png has the start of the manga with a request for cookies at the bottom if that adds to anything. I've tried logging in and out and running the code multiple times but the same error keeps popping up.
> By the way, thanks for coming up with this script! I normally use it for CMOA and it works like a charm :)

Hello,

Are you using the latest version (3042d49) ? BW has just updated their website and this program also got updated.

New version also fix the cmoa 4 pixels bugs and changed the cookie method for cmoa (before can not login), if you are using the old version it's better to update.

If you are using the latest version, then this is a very strange thing and need to do some research, please give the manga URL for future research.

Thank you.

**Comment by xuzhengyi1995** [comment]
And I have never seen the page request for cookies before, if you could maybe use a VPN would help :)

**Comment by beffy3** [comment]
It's working now. Just had to redownload the program since I got it a while back, thanks again.
