### ISSUE TITLE
also works for other binb reader websites

### ISSUE THREAD

**Issue by persia7emily** [xuzhengyi1995/Manga_downloader#45]
THANKS for XU. 

for example gamma plus takeshobo, changes from cmoa_actions

cookies just tap something, it doesn't matter.

line20:
    login_url = 'https://gammaplus.takeshobo.co.jp/'

line 40:
    def check_url(manga_url):
        return manga_url.find('takeshobo.co.jp/manga/') != -1

line 59-72:
        imgs_arr = []
        imgs_height = [0, 400, 800]
        for i in image_elements:
            blob_url = i.get_attribute('src')
            image_data = self.get_file_content_chrome(driver, blob_url)
            part_img = pil_image.open(BytesIO(image_data))
            imgs_arr.append(part_img)

        final_img = pil_image.new('RGB', (844, 1200))

**Comment by xuzhengyi1995** [comment]
Thank you so much, If you would  maybe you could add the new code and create a pull request !

Or I can also add your code into this tool, if you want me to do this, please let me know.

Thank you!

**Comment by persia7emily** [comment]
you add it please~ it's really a powerful tool
