### ISSUE TITLE
downloader.py 和 abstract_website_actions.py 这2个文件出现问题

### ISSUE THREAD

**Issue by CharlesLTH** [xuzhengyi1995/Manga_downloader#6]
![01](https://user-images.githubusercontent.com/33312999/87525535-34c99980-c6bc-11ea-9b53-dd711c9eb02b.JPG)
能够正常运行Bookwalker_Downloade但是Manga_Downloader会像图片那样报错。

**Comment by xuzhengyi1995** [comment]
您好，请问您使用的Python版本是什么，您可以输入`python --version`查看，本程序一般需要Python3.6版本以上方可运行。
另外感谢您的提醒，之后我将会在说明中标注出Python最低版本需求，谢谢！

**Comment by CharlesLTH** [comment]
感谢热心解答 
从2.7换为3.8后完美解决
为大佬点赞
