### ISSUE TITLE
保存下來的jpg檔是壓縮過的？

### ISSUE THREAD

**Issue by kof11** [xuzhengyi1995/Manga_downloader#7]
經過我仔細比對後發現，保存下來的jpg似乎比起原始版本，畫質有略為變差，ringing明顯增加
如果無法避免二次轉檔的話，能否保存成png檔呢？

**Comment by xuzhengyi1995** [comment]
您好，确实是经过压缩的，这点我考虑不周，并且可以使用一定的方法避免转换并输出为png，本人将尽快在下一次提交中进行更新，感谢您的建议，谢谢！

**Comment by xuzhengyi1995** [comment]
您好，已将输出修正为png，谢谢！
