### ISSUE TITLE
same page downloaded twice wth different image resolution

### ISSUE THREAD

**Issue by 0xh3LL0** [xuzhengyi1995/Manga_downloader#72]
found this issue just today when i'm tried to download https://bookwalker.jp/de261095bc-700e-468a-9bb8-8c9fd5d48c51/
manga are downloaded but all images are downloaded twice with different resolution
![res](https://user-images.githubusercontent.com/23132217/141224173-ee39f8c6-3802-45ac-85e4-8e7e34bfb138.png)

**Comment by xuzhengyi1995** [comment]
Please re-download and try the new version, normally this should not happen with the new version.

**Comment by 0xh3LL0** [comment]
i'm using new version

**Comment by persia7emily** [comment]
make the window's size bigger, a bit smaller than two-page view. it works.

**Comment by 0xh3LL0** [comment]
i'll try, thanks!
