### ISSUE TITLE
Manga_downloader with bookwalker

### ISSUE THREAD

**Issue by ann840925** [xuzhengyi1995/Manga_downloader#77]
Sorry, I have a question again.
bookwalker maybe change their codes again.
![error](https://user-images.githubusercontent.com/48669994/146681197-c3eae764-5279-4186-9507-d9c763450fb7.png)
I renew and log out/log in a few times, but it still repo error.

**Comment by 0xh3LL0** [comment]
maybe you can show us the error.png too?

**Comment by ann840925** [comment]
> maybe you can show us the error.png too?

it's just the cover.
![error](https://user-images.githubusercontent.com/48669994/146715627-7c4b2b32-77d7-4d76-8472-0043948d0cb0.png)

**Comment by ann840925** [comment]
It was my fault.
