### ISSUE TITLE
Tutorial Downloading on CMOA

### ISSUE THREAD

**Issue by Ezhbasheil** [xuzhengyi1995/Manga_downloader#78]
Hello,

I tried following the tutorial you did to download the manga but nothing happened, do you think you could do a video tutorial so that it'd be easier to follow?

Thanks in advance

**Comment by Azemar** [comment]
[Something like this](https://www.youtube.com/watch?v=-G2AHjKUVNw)

**Comment by Ezhbasheil** [comment]
> [Something like this](https://www.youtube.com/watch?v=-G2AHjKUVNw)

Yeah but that's for Bookwalker and I don't have any problem downloading on that site. As I specified in the title, it's on cmoa that trying to download doesn't work.

**Comment by persia7emily** [comment]
manga downloader works for cmoa and bookwalker, same steps. try to describe what did you do, let others better know why nothing happened to you.

**Comment by Ezhbasheil** [comment]
> manga downloader works for cmoa and bookwalker, same steps. try to describe what did you do, let others better know why nothing happened to you.

When I paste "window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)" in the console, I get "VM1066:1 Uncaught ReferenceError: NFBR is not defined
    at <anonymous>:1:29" and I don't know where to find the "js". 

And when I try to modify "main.py" by adding the URL, cookie, etc. like it's in the README.md and that I run it, nothing happens.

**Comment by persia7emily** [comment]
> > manga downloader works for cmoa and bookwalker, same steps. try to describe what did you do, let others better know why nothing happened to you.
> 
> When I paste "window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)" in the console, I get "VM1066:1 Uncaught ReferenceError: NFBR is not defined at :1:29" and I don't know where to find the "js".
> 
> And when I try to modify "main.py" by adding the URL, cookie, etc. like it's in the README.md and that I run it, nothing happens.

what you paste is for BW, not CMOA. read carefully.

see https://github.com/xuzhengyi1995/Manga_downloader#how-to-use

**Comment by Ezhbasheil** [comment]
> 

I followed it and it didn't work... I have already put undetected_chromedriver in path and all and followed but nope. I recorded how I did it to show it to you ([https://www.youtube.com/watch?v=ck2C1akSFmo](url)), the video is still being processed by youtube right now so there's now HD so it may be difficult to read depending on when you watch it.

**Comment by persia7emily** [comment]
> > 
> 
> I followed it and it didn't work... I have already put undetected_chromedriver in path and all and followed but nope. I recorded how I did it to show it to you ([https://www.youtube.com/watch?v=ck2C1akSFmo](url)), the video is still being processed by youtube right now so there's now HD so it may be difficult to read depending on when you watch it.

oh honey, you're so fresh to python...



some points:

1. make sure the environment is installed.

this part ↓↓
https://github.com/xuzhengyi1995/Manga_downloader#install-environment--how-to-get-urlcookies

`win+r, cmd`

`pip list`

if they are installed, you'll see it like this.

![微信截图_20220207234750](https://user-images.githubusercontent.com/46820597/152822491-bb32cd52-7ff1-4094-a003-7bd788ef6aee.png)


2. use IDLE to edit and run main.py

find python IDLE in Start Menu or find pythonw.exe in Python folder, open main.py and edit it.

![微信截图_20220207234225](https://user-images.githubusercontent.com/46820597/152823225-fbfbfff0-d81c-45de-9e91-833c95920e8a.png)

![2022-02-07_235135](https://user-images.githubusercontent.com/46820597/152823239-be6efd30-43d7-458b-a30a-07b3905bdf19.png)


try to run it. if there is errors, screenshot.


(i prefer pycharm, more beautiful, like this. but python IDLE is ok)

![2022-02-07_235658](https://user-images.githubusercontent.com/46820597/152824093-f1b5b7dc-d6e4-41f7-8d7d-32be3696b5a6.png)

**Comment by Ezhbasheil** [comment]
I looked and yes I installed selenium, Pillow and undetected-chromedriver
![image](https://user-images.githubusercontent.com/63591132/152860433-4d441cc2-6a80-4ee7-8c0e-ea1c2e8c1d63.png)

and when I click "Run" in Python IDLE it stays on the first line
![image](https://user-images.githubusercontent.com/63591132/152865213-5547dfeb-2897-482e-befc-95109f295eb9.png)

I did something else to wait and see if it changed but when I looked back 10-15 minutes after clicking on "Run" it didn't change.
![image](https://user-images.githubusercontent.com/63591132/152865580-b8554963-b5e8-4b39-a66f-f955de731fee.png)
![image](https://user-images.githubusercontent.com/63591132/152865683-9cd74f06-93dc-45b5-83f3-cc7e41e31d09.png)

**Comment by persia7emily** [comment]
**selenium** needs chromedriver, **undetected-chromedriver** helps to set a chromedriver.

it seems that something wrong with chromedriver, your undetected-chromedriver doesn't play a role. so it cannot open a chrome window.

if chromedriver is correct, it shows 
````
[INFO](root) 2022-02-09 22:40:21 : Find action class, use CmoaJP class.
[INFO](root) 2022-02-09 22:40:21 : Login...
[INFO](root) 2022-02-09 22:40:32 : Login finished...
````


steps to check:
1. python folder is added to path
![2022-02-09_224452](https://user-images.githubusercontent.com/46820597/153225740-228da628-b1dd-4c0c-9e76-a8fdbf5e025b.png)
2. download a chromedriver that fits your chrome, and move it to folder in path
```
chrome://settings/help
https://sites.google.com/chromium.org/driver/
```
![2022-02-09_224615](https://user-images.githubusercontent.com/46820597/153225807-558a7a22-8da5-440a-bc63-cc2db89d4e85.png)

i don't know which will work, so i put a chromedriver.exe in these folder.
![2022-02-09_224758](https://user-images.githubusercontent.com/46820597/153225837-cae2165c-c578-4b0c-9fd5-b19b0d8db23f.png)

then try again

**Comment by persia7emily** [comment]
and you can make the window be seen temporarily,

in downloader.py  search

`option.add_argument('--headless')`

add "#" make it be

`#option.add_argument('--headless')`

then run it, you can see the window works itself

**Comment by Ezhbasheil** [comment]
Now it works. Thank you very much!

**Comment by Ezhbasheil** [comment]
I noticed that when I try to download multiple manga at once, I have that screen:
![image](https://user-images.githubusercontent.com/63591132/153269513-83411f11-5f75-411b-992f-4c66cbe3e1b2.png)

Do you know how to solve this?

**Comment by persia7emily** [comment]
i have reported to author before, no solution now. this problem sometimes happen, you can stop headless (i told about above) to solve it.


and i will avoid download cmoa on 11-1 o'clock japanese time.


发自我的iPhone

------------------ Original ------------------
From: Ezhbasheil ***@***.***&gt;
Date: 周四,2月 10,2022 2:50 上午
To: xuzhengyi1995/Manga_downloader ***@***.***&gt;
Cc: persia7emily ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xuzhengyi1995/Manga_downloader] Tutorial Downloading on CMOA (Issue #78)





 
I noticed that when I try to download multiple manga at once, I have that screen:
 
 
Do you know how to solve this?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ezhbasheil** [comment]
stopping headless didn't solve it but it doesn't matter now that at least I can download
