### ISSUE TITLE
[新方法疑惑]貌似除了已知的封面暂时无法下载外，轻小说的开头彩插也没办法下载下来。

### ISSUE THREAD

**Issue by iPixelOldC** [xuzhengyi1995/Manga_downloader#88]
如题，所以这彩插也是不加密的嘛，那不加密的要怎么弄来着。我记得这里好像分享过，老方案里面有那个下载加密图片。本地打开，来获取图片实际尺寸的方法，在这里应该可以直接用？反正不加密了，我去试试。

  测试书籍 是青春猪头少年第11卷。除封面和开头彩插外(还有末尾的书封)，其他均下载下来了。万分感谢大佬的工作。(已排除网络因素,图片在浏览器里明确加载了)

更新：
  我按老方法，在浏览器网络选项卡里面，成功把未加密的封面按原尺寸手动下载下来了。但是小说开头彩插明确都是被加密的，那为什么新方法没办法获取呢？
  不过小说单页大小是960x1280px。而彩插是2768x2048px，并且看上去彩插也不只一个尺寸，也有单页的1384x2048px，但全都无法下载。所以是尺寸不同或是彩插占了双面的锅？毕竟第1页正常大小的内页封面被解密下载成功了。从第2页开始的彩插就全部失败了（封面是第0面）

再更新：咱用老方案获取彩插，然后混在一起来曲线救国了，不过老方案获取的彩插大小明显小于原版，我宽高都设的2768x2048px。。。看来还是小了，哎。这个还是新方法好用啊QAQ 以及老方案对条漫的支持，好像有点问题，咱这获取的都是黑的。。。我继续调试下

再再更新:在混合时发现...其实不只开头彩插,末尾的书封啥的也都没了,都是尺寸相较于正文不对的图...哎,新方案还是更适合漫画,轻小说还是稍稍麻烦点,不过好在,老方法也不是不能用,可惜不能获取原尺寸的图了

**Comment by cnJJHC** [comment]
Hi,
I can't get the cover of the Manga I have bought.
Try a Chrome app called 'imageassistant Batch Image Downloader'。[LINK HERE](https://chrome.google.com/webstore/detail/imageassistant-batch-imag/dbjbempljhcmhlfpfacalomonjpalpko)

我也遇到了这个问题，目前不能获取漫画封面的，只能先试一下Chrome的imageassistant Batch Image Downloader应用。打开漫画后点击提取本页图片就能保存没被打乱的封面了，被加密的部分仍然不行。

**Comment by iPixelOldC** [comment]
新版本封面和不规则大小彩插均能正常下载了，谢谢大佬(˶‾᷄ ⁻̫ ‾᷅˵)
