### ISSUE TITLE
chromium broken? doesn't save pages

### ISSUE THREAD

**Issue by Cerxi** [xuzhengyi1995/Manga_downloader#91]
It used to work fine, but today I try to download new book and it doesn't work.. I paste `window.i=0;setInterval(()=>{NFBR.a6G.Initializer.Z4p.menu.options.a6l.moveToPage(window.i);console.log(window.i);window.i++;},3000)` and it changes pages, but it doesn't save images anywhere. Maybe bookwalker update something?

**Comment by xuzhengyi1995** [comment]
Have just tried and seems work good, could you provide the link to the manga? Thanks.
PS: Have you added the `--no-sandbox` and also the `--user-data-dir` when you open the browser, thanks.

**Comment by Cerxi** [comment]
Sorry I did not see this until now

I did use --no-sandbox and --user-data-dir before

It was Konosuba TRPG ( https://global.bookwalker.jp/deb4f232d8-940b-447e-9c76-55f6f9710f99/ ) 

But downloader works now. I think it was related to Bookwalker problem with the book; Bookwalker had bad page quality but now they have fixed it and downloader works.
